@echo gen %~nx1...
@tool\protoc.exe -I=. -I=.. --csharp_out=message --csharp_opt=file_extension=.cs --grpc_out=message --plugin=protoc-gen-grpc=tool\grpc_csharp_plugin.exe  %~nx1
@echo finish... 
@pause