// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_game_api.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MO.Protocol {

  /// <summary>Holder for reflection information generated from message_game_api.proto</summary>
  public static partial class MessageGameApiReflection {

    #region Descriptor
    /// <summary>File descriptor for message_game_api.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageGameApiReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZtZXNzYWdlX2dhbWVfYXBpLnByb3RvEgtNTy5Qcm90b2NvbCJECghDb250",
            "YWN0cxISCgpXZWlYaW5Db2RlGAEgASgJEg8KB1FRR3JvdXAYAiABKAkSEwoL",
            "V2VpWGluR3JvdXAYAyABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MO.Protocol.Contacts), global::MO.Protocol.Contacts.Parser, new[]{ "WeiXinCode", "QQGroup", "WeiXinGroup" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Contacts : pb::IMessage<Contacts> {
    private static readonly pb::MessageParser<Contacts> _parser = new pb::MessageParser<Contacts>(() => new Contacts());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Contacts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MO.Protocol.MessageGameApiReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Contacts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Contacts(Contacts other) : this() {
      weiXinCode_ = other.weiXinCode_;
      qQGroup_ = other.qQGroup_;
      weiXinGroup_ = other.weiXinGroup_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Contacts Clone() {
      return new Contacts(this);
    }

    /// <summary>Field number for the "WeiXinCode" field.</summary>
    public const int WeiXinCodeFieldNumber = 1;
    private string weiXinCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string WeiXinCode {
      get { return weiXinCode_; }
      set {
        weiXinCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "QQGroup" field.</summary>
    public const int QQGroupFieldNumber = 2;
    private string qQGroup_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string QQGroup {
      get { return qQGroup_; }
      set {
        qQGroup_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "WeiXinGroup" field.</summary>
    public const int WeiXinGroupFieldNumber = 3;
    private string weiXinGroup_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string WeiXinGroup {
      get { return weiXinGroup_; }
      set {
        weiXinGroup_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Contacts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Contacts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WeiXinCode != other.WeiXinCode) return false;
      if (QQGroup != other.QQGroup) return false;
      if (WeiXinGroup != other.WeiXinGroup) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (WeiXinCode.Length != 0) hash ^= WeiXinCode.GetHashCode();
      if (QQGroup.Length != 0) hash ^= QQGroup.GetHashCode();
      if (WeiXinGroup.Length != 0) hash ^= WeiXinGroup.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (WeiXinCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WeiXinCode);
      }
      if (QQGroup.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(QQGroup);
      }
      if (WeiXinGroup.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(WeiXinGroup);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (WeiXinCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WeiXinCode);
      }
      if (QQGroup.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(QQGroup);
      }
      if (WeiXinGroup.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WeiXinGroup);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Contacts other) {
      if (other == null) {
        return;
      }
      if (other.WeiXinCode.Length != 0) {
        WeiXinCode = other.WeiXinCode;
      }
      if (other.QQGroup.Length != 0) {
        QQGroup = other.QQGroup;
      }
      if (other.WeiXinGroup.Length != 0) {
        WeiXinGroup = other.WeiXinGroup;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            WeiXinCode = input.ReadString();
            break;
          }
          case 18: {
            QQGroup = input.ReadString();
            break;
          }
          case 26: {
            WeiXinGroup = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
